'packages/backend':
- any:
  - changed-files:
    - any-glob-to-any-file: ['packages/backend/**/*']

'packages/backend:test':
- any:
  - changed-files:
    - any-glob-to-any-file: ['packages/backend/test/**/*', 'packages/backend/test-federation/**/*']

'packages/frontend':
- any:
  - changed-files:
    - any-glob-to-any-file: ['packages/frontend/**/*']

'packages/frontend:test':
- any:
  - changed-files:
    - any-glob-to-any-file: ['cypress/**/*']

'packages/sw':
- any:
  - changed-files:
    - any-glob-to-any-file: ['packages/sw/**/*']

'packages/acuaskey-js':
- any:
  - changed-files:
    - any-glob-to-any-file: ['packages/acuaskey-js/**/*']

'packages/acuaskey-js:test':
- any:
  - changed-files:
    - any-glob-to-any-file: ['packages/acuaskey-js/test/**/*', 'packages/acuaskey-js/test-d/**/*']
