services:
  nginx:
    image: nginx:1.27
    volumes:
      - type: bind
        source: ./certificates/rootCA.crt
        target: /etc/nginx/certificates/rootCA.crt
        read_only: true
    healthcheck:
      test: service nginx status
      interval: 5s
      retries: 20

  Acuaskey:
    image: node:20
    env_file:
      - ./.config/docker.env
    environment:
      - NODE_ENV=production
      - COREPACK_DEFAULT_TO_LATEST=0
    volumes:
      - type: bind
        source: ../../../built
        target: /Acuaskey/built
        read_only: true
      - type: bind
        source: ../assets
        target: /Acuaskey/packages/backend/assets
        read_only: true
      - type: bind
        source: ../built
        target: /Acuaskey/packages/backend/built
        read_only: true
      - type: bind
        source: ../migration
        target: /Acuaskey/packages/backend/migration
        read_only: true
      - type: bind
        source: ../ormconfig.js
        target: /Acuaskey/packages/backend/ormconfig.js
        read_only: true
      - type: bind
        source: ../package.json
        target: /Acuaskey/packages/backend/package.json
        read_only: true
      - type: bind
        source: ../../Acuaskey-js/built
        target: /Acuaskey/packages/acuaskey-js/built
        read_only: true
      - type: bind
        source: ../../Acuaskey-js/package.json
        target: /Acuaskey/packages/acuaskey-js/package.json
        read_only: true
      - type: bind
        source: ../../misskey-reversi/built
        target: /Acuaskey/packages/misskey-reversi/built
        read_only: true
      - type: bind
        source: ../../misskey-reversi/package.json
        target: /Acuaskey/packages/misskey-reversi/package.json
        read_only: true
      - type: bind
        source: ../../../healthcheck.sh
        target: /Acuaskey/healthcheck.sh
        read_only: true
      - type: bind
        source: ../../../package.json
        target: /Acuaskey/package.json
        read_only: true
      - type: bind
        source: ../../../pnpm-lock.yaml
        target: /Acuaskey/pnpm-lock.yaml
        read_only: true
      - type: bind
        source: ../../../pnpm-workspace.yaml
        target: /Acuaskey/pnpm-workspace.yaml
        read_only: true
      - type: bind
        source: ./certificates/rootCA.crt
        target: /usr/local/share/ca-certificates/rootCA.crt
        read_only: true
    working_dir: /Acuaskey
    command: >
      bash -c "
        corepack enable && corepack prepare
        pnpm -F backend migrate
        pnpm -F backend start
      "
    healthcheck:
      test: bash /Acuaskey/healthcheck.sh
      interval: 5s
      retries: 20

  db:
    image: postgres:15-alpine
    env_file:
      - ./.config/docker.env
    volumes:
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 5s
      retries: 20
