name: API report (Acuaskey.js)

on:
  push:
    paths:
      - packages/acuaskey-js/**
      - .github/workflows/api-acuaskey-js.yml
  pull_request:
    paths:
      - packages/acuaskey-js/**
      - .github/workflows/api-acuaskey-js.yml

env:
  COREPACK_DEFAULT_TO_LATEST: 0

jobs:
  report:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v4.1.0
        with:
          node-version-file: '.node-version'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Build
        run: pnpm --filter acuaskey-js build

      - name: Check files
        run: ls packages/acuaskey-js/built

      - name: API report
        run: pnpm --filter acuaskey-js api-prod

      - name: Show report
        if: always()
        run: cat packages/acuaskey-js/temp/acuaskey-js.api.md
